apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: piky-blog
  description: My personal blog to keep technical notes.
  annotations:
    github.com/project-slug: piky/blog
    backstage.io/managed-by-location: url:http://github.com/backstage/piky/blog
  tags:
    - blog
    - github-pages
    - ssg
  links:
    - url: https://piky.github.io/blog
      title: Blog

spec:
  type: website
  lifecycle: experimental
  owner: Wijai Thongsom
  system: static-site-generator