name: Test deployment

on:
  push:
    branches-ignore:
      - main
      - gh-pages
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Test build website
        run: bun run build

  pull-request:
    name: Create Pull Request
    needs: test-deploy
    permissions: write-all
    environment: 
      name: draft 
      url: ${{ steps.create_pr.outputs.url }}
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get full history
          ref: ${{ github.head_ref }}
      - name: Fetch all branches
        run: |
          git fetch origin main:main
      - name: Create PR
        id: create_pr
        run: |
          pr_url=$(gh pr create --fill --base main --head ${{ github.ref_name }} || gh pr list --head ${{ github.ref_name }} --json url -q ".[0].url")
          echo "url=$pr_url" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
