name: Test deployment

on:
  push:
    branches-ignore:
      - main
      - gh-pages
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Test build website
        run: yarn build

  pull-request:
    name: Create Pull Request
    needs: test-deploy
    permissions: write-all
    environment: 
      name: pull-request-url
      url: ${{ steps.create_pr.outputs.url }}
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get full history
          ref: ${{ github.head_ref }}
      - name: Fetch all branches
        run: |
          git fetch origin main:main
      - name: Create PR
        id: create_pr
        run: |
          set -e
          if ! pr_url=$(gh pr create --base main --head ${{ github.ref_name }} --title "Update from ${{ github.ref_name }}" --body "Automated PR"); then
            if ! pr_url=$(gh pr list --head ${{ github.ref_name }} --json url -q ".[0].url"); then
              echo "Failed to create or find pull request"
              exit 1
            fi
          fi
          echo "url=$pr_url" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
