name: Test deployment

on:
  push:
    branches-ignore:
      - main
      - gh-pages
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Test build website
        run: yarn build

  pull-request:
    name: Create Pull Request
    needs: test-deploy

    permissions: write-all

    environment:
      name: pull-request
      url: ${{ github.event.pull_request.html_url }}

    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: Create PR
        id: create_pr
        run: |
          gh pr create --title "My Pull Request" --body "Description" || gh pr edit --title "My Pull Request" --body "Description"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
